Repository GoodTripProject/GoodTripAndroid, pull requests merged in 2024-06, with the labels that each got.

#56 [UI] Add recursive chain of Followers
  app/src/main/java/ru/hse/goodtrip/data/UsersRepository.java
  app/src/main/java/ru/hse/goodtrip/navigation/GtNavigationGraphMain.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/following/ProfileFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedAdapter.java
  app/src/main/res/drawable/heart.png
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_following.xml
  app/src/main/res/layout/item_post_trip.xml
  app/src/main/res/navigation/profile_navigation_graph.xml
Labels: bug, enhancement, front-end

#57 [HOTFIX] Follow button
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedAdapter.java
Labels: bug, front-end

#58 [UI][Test] Room tests
  app/build.gradle.kts
  app/src/androidTest/java/ru/hse/goodtrip/AppInstrumentedTest.java
  app/src/androidTest/java/ru/hse/goodtrip/GtNavigationUITest.java
  app/src/androidTest/java/ru/hse/goodtrip/RoomImplementationTest.java
  app/src/androidTest/java/ru/hse/goodtrip/TestUtil.java
  app/src/androidTest/java/ru/hse/goodtrip/ui/FeedScreenTest.java
  app/src/main/java/ru/hse/goodtrip/room/RoomImplementation.java
  app/src/main/java/ru/hse/goodtrip/ui/authentication/AuthViewModel.java
  app/src/test/java/ru/hse/goodtrip/ExampleUnitTest.java
Labels: front-end

#59 Add network interactions about social
  app/src/main/java/ru/hse/goodtrip/data/AbstractRepository.java
  app/src/main/java/ru/hse/goodtrip/data/CommunicationRepository.java
  app/src/main/java/ru/hse/goodtrip/data/PlacesRepository.java
  app/src/main/java/ru/hse/goodtrip/data/TripRepository.java
  app/src/main/java/ru/hse/goodtrip/data/UsersRepository.java
  app/src/main/java/ru/hse/goodtrip/network/NetworkManager.java
  app/src/main/java/ru/hse/goodtrip/network/authentication/LoginService.java
  app/src/main/java/ru/hse/goodtrip/network/authentication/model/UrlHandler.java
  app/src/main/java/ru/hse/goodtrip/network/places/model/PlaceRequest.java
  app/src/main/java/ru/hse/goodtrip/network/places/model/PlaceResponse.java
  app/src/main/java/ru/hse/goodtrip/network/social/CommunicationService.java
  app/src/main/java/ru/hse/goodtrip/network/social/entities/User.java
  app/src/main/java/ru/hse/goodtrip/network/trips/TripService.java
  app/src/main/java/ru/hse/goodtrip/ui/authentication/AuthViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFragment.java
Labels: enhancement

#61 [BREAKING] Handle case if user has no main photo
  app/src/main/java/ru/hse/goodtrip/ui/authentication/AuthViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingViewModel.java
Labels: bug

#64 [UI] Fix small UI issues in Profile.
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedAdapter.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/post/PostDetailsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/post/PostNotesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFormState.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFragment.java
  app/src/main/res/drawable/baseline_south_america_24.xml
  app/src/main/res/drawable/mapnnn.png
  app/src/main/res/drawable/new_map.png
  app/src/main/res/drawable/new_new_map.png
  app/src/main/res/drawable/no_photo.png
  app/src/main/res/drawable/noimage.png
  app/src/main/res/layout/action_bar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_post_details.xml
  app/src/main/res/layout/fragment_post_editor.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/layout/item_post_trip.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/feed_navigation_graph.xml
  app/src/main/res/navigation/profile_navigation_graph.xml
Labels: enhancement, front-end

#65 Style refactor
  app/src/main/java/ru/hse/goodtrip/MainActivity.java
  app/src/main/java/ru/hse/goodtrip/navigation/GtNavigationGraphMain.java
  app/src/main/java/ru/hse/goodtrip/room/AppPreferences.java
  app/src/main/java/ru/hse/goodtrip/room/RoomImplementation.java
  app/src/main/java/ru/hse/goodtrip/room/entities/UserEntity.java
  app/src/main/java/ru/hse/goodtrip/ui/map/CustomInfoWindowAdapter.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/AddFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/FollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/followers/ProfileFollowingViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/MyTripsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/MyTripsViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorDialogWindows.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedAdapter.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/FeedViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/post/PostDetailsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/post/PostFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/feed/post/PostNotesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripDialogWindows.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFormState.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripViewModel.java
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/icon_edit.png
  app/src/main/res/drawable/mapnnn.png
  app/src/main/res/drawable/new_map.png
  app/src/main/res/drawable/new_new_map.png
  app/src/main/res/drawable/no_photo.png
  app/src/main/res/drawable/wave__1_.xml
Labels: front-end

#63 Update README
  README.md
Labels: documentation
