Repository GoodTripProject/GoodTripAndroid, pull requests merged in 2024-05, with the labels that each got.

#44 [UI][Maps] Add trip-as-paths appearing + referencing to postpage when InfoWindow is clicked
  app/src/main/java/ru/hse/goodtrip/navigation/GtNavigationGraphMain.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFragment.java
  app/src/main/res/drawable/custom_info_bubble.9.png
  app/src/main/res/layout/custom_info_contents.xml
  app/src/main/res/layout/custom_info_window.xml
  app/src/main/res/layout/item_place.xml
Labels: enhancement, front-end

#45 Update getting coordinates for places with new version of API
  app/src/main/java/ru/hse/goodtrip/data/PlacesRepository.java
  app/src/main/java/ru/hse/goodtrip/network/places/PlacesService.java
  app/src/main/java/ru/hse/goodtrip/network/places/model/PlaceRequest.java
Labels: enhancement

#46 [UI] [Room] Fix credentials pulling from Room + log out
  app/src/main/java/ru/hse/goodtrip/data/UsersRepository.java
  app/src/main/java/ru/hse/goodtrip/room/AppPreferences.java
  app/src/main/java/ru/hse/goodtrip/room/RoomImplementation.java
  app/src/main/java/ru/hse/goodtrip/room/dao/UserDao.java
  app/src/main/java/ru/hse/goodtrip/ui/authentication/LoginFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/res/drawable/baseline_exit_to_app_24.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, front-end

#48 [UI][Places] Implement PlacesFragment, places rendering
  app/src/main/AndroidManifest.xml
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/res/layout/fragment_places.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, front-end

#50 Create network interaction about getting places from API
  app/src/main/java/ru/hse/goodtrip/data/PlacesRepository.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/places/PlacesViewModel.java
Labels: enhancement

#49 [UI][Profile] Edit mode in PostEditor
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorViewModel.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripViewModel.java
  app/src/main/res/drawable/icon_edit12.png
  app/src/main/res/layout/fragment_plan_trip.xml
  app/src/main/res/layout/fragment_post_editor.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, front-end

#51 [UI][MyTrips] TripState appearing
  app/src/main/java/ru/hse/goodtrip/navigation/GtNavigationGraphMain.java
  app/src/main/java/ru/hse/goodtrip/ui/map/MapsFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/MyTripsFragment.java
  app/src/main/res/layout/item_trip_profile.xml
Labels: enhancement, front-end

#53 [Profile][UI] Uploading images by Camera or by Gallery for post and notes.
  app/src/main/java/ru/hse/goodtrip/data/model/User.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/AbstractPlace.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/City.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/Coordinates.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/Country.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/CountryVisit.java
  app/src/main/java/ru/hse/goodtrip/data/model/trips/Note.java
  app/src/main/java/ru/hse/goodtrip/navigation/GtNavigationGraphMain.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorViewModel.java
  app/src/main/res/drawable/white_shaped_background.xml
  app/src/main/res/layout/fragment_add_new_note_dialog.xml
  app/src/main/res/layout/fragment_post_editor.xml
Labels: enhancement, front-end

#54 Make uploading photos via Firebase
  app/build.gradle.kts
  app/src/main/java/ru/hse/goodtrip/MainActivity.java
  app/src/main/java/ru/hse/goodtrip/data/UsersRepository.java
  app/src/main/java/ru/hse/goodtrip/data/model/User.java
  app/src/main/java/ru/hse/goodtrip/network/authentication/LoginService.java
  app/src/main/java/ru/hse/goodtrip/network/authentication/model/UrlHandler.java
  app/src/main/java/ru/hse/goodtrip/network/firebase/FirebaseUtils.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  build.gradle.kts
Labels: enhancement
