Repository GoodTripProject/GoodTripAndroid, pull requests merged in 2024-04, with the labels that each got.

#29 Create LocalStorage
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/ru/hse/goodtrip/MainActivity.java
  app/src/main/java/ru/hse/goodtrip/data/UsersRepository.java
  app/src/main/java/ru/hse/goodtrip/room/AppPreferences.java
  app/src/main/java/ru/hse/goodtrip/room/LocalStorage.java
  app/src/main/java/ru/hse/goodtrip/room/RoomImplementation.java
  app/src/main/java/ru/hse/goodtrip/room/dao/UserDao.java
  app/src/main/java/ru/hse/goodtrip/room/entities/UserEntity.java
  app/src/main/java/ru/hse/goodtrip/ui/authentication/LoginFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/ProfileFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/MyTripsViewModel.java
Labels: enhancement

#34 [BREAKING] Add note issues fixes
  app/src/main/java/ru/hse/goodtrip/network/trips/model/AddNoteRequest.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorViewModel.java
Labels: bug, enhancement

#40 [UI] Dialog windows
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorDialogWindows.java
  app/src/main/java/ru/hse/goodtrip/ui/profile/mytrips/PostEditorFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/DialogAddNewDestinationFragment.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripDialogWindows.java
  app/src/main/java/ru/hse/goodtrip/ui/trips/plantrip/PlanTripFragment.java
  app/src/main/res/drawable/baseline_close_24.xml
  app/src/main/res/layout/fragment_add_new_note_dialog.xml
  app/src/main/res/layout/fragment_blank.xml
  app/src/main/res/layout/fragment_dialog_add_new_destination.xml
Labels: front-end
